// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAMPHrDZXRg4iPxizs2CoWwlCAoFLDaG4',
    appId: '1:775815063846:web:a025c02d1cbde979c839e7',
    messagingSenderId: '775815063846',
    projectId: 'my-second-project-dfeec',
    authDomain: 'my-second-project-dfeec.firebaseapp.com',
    storageBucket: 'my-second-project-dfeec.appspot.com',
    measurementId: 'G-SR999GSST6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Is3kA9_vHAv6A32Rt9A-7nhQHd_rwA0',
    appId: '1:775815063846:android:1ba2eb2c8120cf1dc839e7',
    messagingSenderId: '775815063846',
    projectId: 'my-second-project-dfeec',
    storageBucket: 'my-second-project-dfeec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIIxk_RlkljVPD36KK7z903Tf9m4OE0_I',
    appId: '1:775815063846:ios:cd3b85cfa03035b5c839e7',
    messagingSenderId: '775815063846',
    projectId: 'my-second-project-dfeec',
    storageBucket: 'my-second-project-dfeec.appspot.com',
    iosBundleId: 'com.example.nov20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIIxk_RlkljVPD36KK7z903Tf9m4OE0_I',
    appId: '1:775815063846:ios:8b669ac3d792e17bc839e7',
    messagingSenderId: '775815063846',
    projectId: 'my-second-project-dfeec',
    storageBucket: 'my-second-project-dfeec.appspot.com',
    iosBundleId: 'com.example.nov20.RunnerTests',
  );
}
